### ISSUE TITLE
Quick start context type file

### ISSUE THREAD

**Issue by soukudom** [CESNET/ALF#1]
Please check "def create_context(context_type, **options) -> None" in "alf/d_manager.py"
There are two "if" statements instead of "elif". See below

 if context_type == "file":
            d_0_path = options.get("d_0_path")
            DbProvider._db = DManagerFile(d_0_path)
if context_type == "dataframe": ===============> should be elif
            d_0_path = options.get("d_0_path")
            DbProvider._db = DManagerDataFrame(d_0_path)
else:
            raise ValueError("Unknown database type")

**Comment by jaroslavpesek** [comment]
Fixed.
